---
spring:
  config.activate.on-profile: default
cds:
  datasource:
    auto-config.enabled: false

  messaging.services:
    - name: "messaging"
      kind: "enterprise-messaging"
      format: "cloudevents"
      publishPrefix: '$namespace/ce/'
      subscribePrefix: '$namespace/ce/'